/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MK64FN1M0xxx12
package_id: MK64FN1M0VLL12
mcu_data: ksdk2_0
processor_version: 7.0.1
board: FRDM-K64F
pin_labels:
- {pin_num: '90', pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, label: /DONEn, identifier: DONEn}
- {pin_num: '91', pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, label: /DOK, identifier: DOK}
- {pin_num: '57', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20}
- {pin_num: '35', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI}
- {pin_num: '69', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, label: /BTN_MENU, identifier: BTN_MENU}
- {pin_num: '36', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO}
- {pin_num: '72', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, label: /BTN_PLAY, identifier: BTN_PLAY}
- {pin_num: '73', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: /BTN_PREV, identifier: BTN_PREV}
- {pin_num: '64', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, label: /LCD_RESET, identifier: LCD_RESET}
- {pin_num: '65', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, label: /LCD_DCRS, identifier: LCD_DCRS}
- {pin_num: '71', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, label: /BTN_SELECT, identifier: BTN_SELECT}
- {pin_num: '80', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7}
- {pin_num: '81', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0}
- {pin_num: '77', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, label: /LED_SENSE_3_3V, identifier: LED_SENSE_3_3V}
- {pin_num: '79', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FB_AD8}
- {pin_num: '70', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, label: /BTN_NEXT, identifier: BTN_NEXT}
- {pin_num: '84', pin_signal: PTC12/UART4_RTS_b/FB_AD27/FTM3_FLT0}
- {pin_num: '76', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, label: /PWR_EN_5Vn, identifier: PWR_EN_5Vn}
- {pin_num: '93', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: /DBG1, identifier: DBG1}
- {pin_num: '95', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL, label: /LED_DATA, identifier: LED_DATA}
- {pin_num: '96', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, label: /DBG4, identifier: DBG4}
- {pin_num: '94', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: /DBG2, identifier: DBG2}
- {pin_num: '32', pin_signal: ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN}
- {pin_num: '31', pin_signal: ADC0_SE17/PTE24/UART4_TX/I2C0_SCL/EWM_OUT_b}
- {pin_num: '26', pin_signal: VREF_OUT/CMP1_IN5/CMP0_IN5/ADC1_SE18}
- {pin_num: '21', pin_signal: ADC1_DM0/ADC0_DM3}
- {pin_num: '18', pin_signal: ADC0_DP0/ADC1_DP3}
- {pin_num: '19', pin_signal: ADC0_DM0/ADC1_DM3}
- {pin_num: '20', pin_signal: ADC1_DP0/ADC0_DP3}
- {pin_num: '33', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN}
- {pin_num: '27', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, label: /DAC_AUDIO, identifier: DAC_AUDIO}
- {pin_num: '66', pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, label: /LCD_LED, identifier: LCD_LED}
- {pin_num: '17', pin_signal: ADC1_DM1}
- {pin_num: '16', pin_signal: ADC1_DP1}
- {pin_num: '15', pin_signal: ADC0_DM1}
- {pin_num: '14', pin_signal: ADC0_DP1}
- {pin_num: '55', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, label: /AUD_I2C_SCL, identifier: AUD_I2C_SCL}
- {pin_num: '56', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, label: /AUD_I2C_SDA, identifier: AUD_I2C_SDA}
- {pin_num: '58', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, label: /LCD_CSn, identifier: LCD_CSn}
- {pin_num: '59', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, label: /LCD_SCK, identifier: LCD_SCK}
- {pin_num: '83', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, label: /BAT_I2C_SCL, identifier: BAT_I2C_SDA}
- {pin_num: '82', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: /BAT_I2C_SCL, identifier: BAT_I2C_SCL}
- {pin_num: '38', pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, label: /NMI, identifier: NMI}
- {pin_num: '78', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/I2S0_MCLK, label: /BTN_SELECT, identifier: BTN_SELECT}
- {pin_num: '52', pin_signal: RESET_b}
- {pin_num: '6', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0, label: /SD_DAT2, identifier: SD_DAT2}
- {pin_num: '5', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0, label: /SD_DAT3, identifier: SD_DAT3}
- {pin_num: '4', pin_signal: ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT, label: /SD_CMD, identifier: SD_CMD}
- {pin_num: '3', pin_signal: ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2, label: /SD_CLK, identifier: SD_CLK}
- {pin_num: '2', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN, label: /SD_DAT0, identifier: SD_DAT0}
- {pin_num: '1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, label: /SD_DAT1, identifier: SD_DAT1}
- {pin_num: '7', pin_signal: PTE6/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/FTM3_CH1/USB_SOF_OUT}
- {pin_num: '98', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK}
- {pin_num: '100', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, label: /SD_DETECT, identifier: SD_DETECT}
- {pin_num: '97', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0}
- {pin_num: '99', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT}
- {pin_num: '92', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, label: /CHG, identifier: CHG}
- {pin_num: '86', pin_signal: PTC14/UART4_RX/FB_AD25, label: /PWR_EN_3V3, identifier: PWR_EN_3V3}
- {pin_num: '87', pin_signal: PTC15/UART4_TX/FB_AD24}
- {pin_num: '54', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB, label: /ENC_B, identifier: ENC_B}
- {pin_num: '53', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA, label: /ENC_A, identifier: ENC_A}
- {pin_num: '50', pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, label: /XTALN, identifier: XTALP}
- {pin_num: '43', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB, label: /I2S_WS, identifier: I2S_WS}
- {pin_num: '42', pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA, label: /I2S_SDI, identifier: I2S_SDI}
- {pin_num: '39', pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, label: /I2S_CLK, identifier: I2S_CLK}
- {pin_num: '44', pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, label: /HPR_SENSE, identifier: HPR_SENSE}
- {pin_num: '85', pin_signal: PTC13/UART4_CTS_b/FB_AD26, label: /LOW_BATn, identifier: LOW_BATn}
- {pin_num: '62', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, label: /LCD_MOSI, identifier: LCD_MOSI}
- {pin_num: '63', pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, label: /LCD_MISO, identifier: LCD_MISO}
- {pin_num: '37', pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO}
- {pin_num: '34', pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/JTAG_TCLK/SWD_CLK/EZP_CLK}
- {pin_num: '68', pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, label: /LED_DATA, identifier: LED_DATA}
- {pin_num: '67', pin_signal: PTB21/SPI2_SCK/FB_AD30/CMP1_OUT}
- {pin_num: '13', pin_signal: VREGIN, label: /P3V3_MCU, identifier: P3V3_MCU}
- {pin_num: '29', pin_signal: EXTAL32}
- {pin_num: '28', pin_signal: XTAL32}
- {pin_num: '51', pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, label: /XTALN, identifier: XTALN}
- {pin_num: '30', pin_signal: VBAT}
- {pin_num: '8', pin_signal: VDD16}
- {pin_num: '22', pin_signal: VDDA}
- {pin_num: '12', pin_signal: VOUT33, label: /VOUT3V3, identifier: VOUT3V3}
- {pin_num: '10', pin_signal: USB0_DP, label: /USB_P, identifier: USB_P}
- {pin_num: '11', pin_signal: USB0_DM, label: /USB_N, identifier: USB_N}
- {pin_num: '23', pin_signal: VREFH}
- {pin_num: '45', pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, label: /HPL_SENSE, identifier: HPL_SENSE}
- {pin_num: '46', pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1}
- {pin_num: '47', pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK, label: /I2S_MCLK, identifier: I2S_MCLK}
- {pin_num: '24', pin_signal: VREFL}
- {pin_num: '9', pin_signal: VSS17}
- {pin_num: '40', pin_signal: VDD63}
- {pin_num: '25', pin_signal: VSSA}
- {pin_num: '41', pin_signal: VSS64}
- {pin_num: '48', pin_signal: VDD80}
- {pin_num: '49', pin_signal: VSS81}
- {pin_num: '61', pin_signal: VDD110}
- {pin_num: '75', pin_signal: VDD124}
- {pin_num: '89', pin_signal: VDD140}
- {pin_num: '60', pin_signal: VSS109}
- {pin_num: '74', pin_signal: VSS123}
- {pin_num: '88', pin_signal: VSS139}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: '', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: I2S0, signal: TX_BCLK, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, direction: OUTPUT}
  - {pin_num: '42', peripheral: I2S0, signal: TXD0, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA}
  - {pin_num: '43', peripheral: I2S0, signal: TX_FS, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB, direction: OUTPUT}
  - {pin_num: '47', peripheral: I2S0, signal: MCLK, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK, direction: OUTPUT}
  - {pin_num: '44', peripheral: GPIOA, signal: 'GPIO, 14', pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, direction: INPUT,
    gpio_interrupt: kPORT_InterruptOrDMADisabled}
  - {pin_num: '45', peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, direction: INPUT}
  - {pin_num: '53', peripheral: FTM1, signal: 'QD_PH, A', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA}
  - {pin_num: '54', peripheral: FTM1, signal: 'QD_PH, B', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB}
  - {pin_num: '55', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3}
  - {pin_num: '56', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0}
  - {pin_num: '58', peripheral: SPI1, signal: PCS0_SS, pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, direction: OUTPUT}
  - {pin_num: '59', peripheral: SPI1, signal: SCK, pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, direction: OUTPUT}
  - {pin_num: '63', peripheral: SPI1, signal: SIN, pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b}
  - {pin_num: '62', peripheral: SPI1, signal: SOUT, pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN}
  - {pin_num: '64', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, direction: OUTPUT}
  - {pin_num: '65', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, direction: OUTPUT}
  - {pin_num: '66', peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '72', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, direction: INPUT,
    pull_select: up, pull_enable: enable, passive_filter: disable}
  - {pin_num: '73', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, direction: INPUT, pull_select: up,
    pull_enable: enable, passive_filter: disable}
  - {pin_num: '76', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '77', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, direction: INPUT}
  - {pin_num: '69', peripheral: GPIOB, signal: 'GPIO, 23', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, direction: INPUT, pull_select: up, pull_enable: enable, passive_filter: disable}
  - {pin_num: '82', peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5}
  - {pin_num: '83', peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b}
  - {pin_num: '85', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: PTC13/UART4_CTS_b/FB_AD26, direction: INPUT}
  - {pin_num: '86', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25, direction: OUTPUT}
  - {pin_num: '90', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, direction: INPUT}
  - {pin_num: '91', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, direction: INPUT}
  - {pin_num: '92', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, direction: INPUT}
  - {pin_num: '93', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: OUTPUT, digital_filter: disable}
  - {pin_num: '94', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: OUTPUT}
  - {pin_num: '96', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, direction: OUTPUT}
  - {pin_num: '3', peripheral: SDHC, signal: DCLK, pin_signal: ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2, pull_select: up, pull_enable: enable}
  - {pin_num: '5', peripheral: SDHC, signal: 'DATA, 3', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0, pull_select: up, pull_enable: enable}
  - {pin_num: '6', peripheral: SDHC, signal: 'DATA, 2', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0, pull_select: up, pull_enable: enable}
  - {pin_num: '2', peripheral: SDHC, signal: 'DATA, 0', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN, pull_select: up,
    pull_enable: enable}
  - {pin_num: '4', peripheral: SDHC, signal: CMD, pin_signal: ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT, pull_select: up, pull_enable: enable}
  - {pin_num: '1', peripheral: SDHC, signal: 'DATA, 1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '71', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, direction: INPUT, pull_select: up,
    pull_enable: enable, passive_filter: disable}
  - {pin_num: '50', peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0}
  - {pin_num: '51', peripheral: OSC, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1}
  - {pin_num: '38', peripheral: SystemControl, signal: NMI, pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b}
  - {pin_num: '100', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge,
    pull_select: up, pull_enable: enable}
  - {pin_num: '27', peripheral: DAC0, signal: OUT, pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: '11', peripheral: USB0, signal: DM, pin_signal: USB0_DM}
  - {pin_num: '10', peripheral: USB0, signal: DP, pin_signal: USB0_DP}
  - {pin_num: '12', peripheral: USB0, signal: VOUT33, pin_signal: VOUT33}
  - {pin_num: '13', peripheral: USB0, signal: VREGIN, pin_signal: VREGIN}
  - {pin_num: '70', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, direction: INPUT, pull_select: up,
    pull_enable: enable, passive_filter: disable}
  - {pin_num: '95', peripheral: SPI0, signal: SOUT, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL, identifier: ''}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t HPR_SENSE_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA14 (pin 44)  */
    GPIO_PinInit(HPR_SENSE_GPIO, HPR_SENSE_PIN, &HPR_SENSE_config);

    gpio_pin_config_t HPL_SENSE_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA15 (pin 45)  */
    GPIO_PinInit(HPL_SENSE_GPIO, HPL_SENSE_PIN, &HPL_SENSE_config);

    gpio_pin_config_t LCD_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 64)  */
    GPIO_PinInit(LCD_RESET_GPIO, LCD_RESET_PIN, &LCD_RESET_config);

    gpio_pin_config_t LCD_DCRS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 65)  */
    GPIO_PinInit(LCD_DCRS_GPIO, LCD_DCRS_PIN, &LCD_DCRS_config);

    gpio_pin_config_t LCD_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin 66)  */
    GPIO_PinInit(LCD_LED_GPIO, LCD_LED_PIN, &LCD_LED_config);

    gpio_pin_config_t BTN_MENU_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB23 (pin 69)  */
    GPIO_PinInit(BTN_MENU_GPIO, BTN_MENU_PIN, &BTN_MENU_config);

    gpio_pin_config_t BTN_NEXT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 70)  */
    GPIO_PinInit(BTN_NEXT_GPIO, BTN_NEXT_PIN, &BTN_NEXT_config);

    gpio_pin_config_t BTN_SELECT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 71)  */
    GPIO_PinInit(BTN_SELECT_GPIO, BTN_SELECT_PIN, &BTN_SELECT_config);

    gpio_pin_config_t BTN_PLAY_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 72)  */
    GPIO_PinInit(BTN_PLAY_GPIO, BTN_PLAY_PIN, &BTN_PLAY_config);

    gpio_pin_config_t BTN_PREV_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 73)  */
    GPIO_PinInit(BTN_PREV_GPIO, BTN_PREV_PIN, &BTN_PREV_config);

    gpio_pin_config_t PWR_EN_5Vn_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 76)  */
    GPIO_PinInit(PWR_EN_5Vn_GPIO, PWR_EN_5Vn_PIN, &PWR_EN_5Vn_config);

    gpio_pin_config_t LED_SENSE_3_3V_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 77)  */
    GPIO_PinInit(LED_SENSE_3_3V_GPIO, LED_SENSE_3_3V_PIN, &LED_SENSE_3_3V_config);

    gpio_pin_config_t LOW_BATn_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC13 (pin 85)  */
    GPIO_PinInit(LOW_BATn_GPIO, LOW_BATn_PIN, &LOW_BATn_config);

    gpio_pin_config_t PWR_EN_3V3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC14 (pin 86)  */
    GPIO_PinInit(PWR_EN_3V3_GPIO, PWR_EN_3V3_PIN, &PWR_EN_3V3_config);

    gpio_pin_config_t DONEn_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 90)  */
    GPIO_PinInit(DONEn_GPIO, DONEn_PIN, &DONEn_config);

    gpio_pin_config_t DOK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC17 (pin 91)  */
    GPIO_PinInit(DOK_GPIO, DOK_PIN, &DOK_config);

    gpio_pin_config_t CHG_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC18 (pin 92)  */
    GPIO_PinInit(CHG_GPIO, CHG_PIN, &CHG_config);

    gpio_pin_config_t DBG1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin 93)  */
    GPIO_PinInit(DBG1_GPIO, DBG1_PIN, &DBG1_config);

    gpio_pin_config_t DBG2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 94)  */
    GPIO_PinInit(DBG2_GPIO, DBG2_PIN, &DBG2_config);

    gpio_pin_config_t DBG4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 96)  */
    GPIO_PinInit(DBG4_GPIO, DBG4_PIN, &DBG4_config);

    gpio_pin_config_t SD_DETECT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 100)  */
    GPIO_PinInit(SD_DETECT_GPIO, SD_DETECT_PIN, &SD_DETECT_config);

    /* PORTA12 (pin 42) is configured as I2S0_TXD0 */
    PORT_SetPinMux(I2S_SDI_PORT, I2S_SDI_PIN, kPORT_MuxAlt6);

    /* PORTA13 (pin 43) is configured as I2S0_TX_FS */
    PORT_SetPinMux(I2S_WS_PORT, I2S_WS_PIN, kPORT_MuxAlt6);

    /* PORTA14 (pin 44) is configured as PTA14 */
    PORT_SetPinMux(HPR_SENSE_PORT, HPR_SENSE_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA14 (pin 44): Interrupt/DMA request is disabled */
    PORT_SetPinInterruptConfig(HPR_SENSE_PORT, HPR_SENSE_PIN, kPORT_InterruptOrDMADisabled);

    /* PORTA15 (pin 45) is configured as PTA15 */
    PORT_SetPinMux(HPL_SENSE_PORT, HPL_SENSE_PIN, kPORT_MuxAsGpio);

    /* PORTA17 (pin 47) is configured as I2S0_MCLK */
    PORT_SetPinMux(I2S_MCLK_PORT, I2S_MCLK_PIN, kPORT_MuxAlt6);

    /* PORTA18 (pin 50) is configured as EXTAL0 */
    PORT_SetPinMux(XTALP_PORT, XTALP_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin 51) is configured as XTAL0 */
    PORT_SetPinMux(XTALN_PORT, XTALN_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA4 (pin 38) is configured as NMI_b */
    PORT_SetPinMux(NMI_PORT, NMI_PIN, kPORT_MuxAlt7);

    /* PORTA5 (pin 39) is configured as I2S0_TX_BCLK */
    PORT_SetPinMux(I2S_CLK_PORT, I2S_CLK_PIN, kPORT_MuxAlt6);

    /* PORTB0 (pin 53) is configured as FTM1_QD_PHA */
    PORT_SetPinMux(ENC_A_PORT, ENC_A_PIN, kPORT_MuxAlt6);

    /* PORTB1 (pin 54) is configured as FTM1_QD_PHB */
    PORT_SetPinMux(ENC_B_PORT, ENC_B_PIN, kPORT_MuxAlt6);

    /* PORTB10 (pin 58) is configured as SPI1_PCS0 */
    PORT_SetPinMux(LCD_CSn_PORT, LCD_CSn_PIN, kPORT_MuxAlt2);

    /* PORTB11 (pin 59) is configured as SPI1_SCK */
    PORT_SetPinMux(LCD_SCK_PORT, LCD_SCK_PIN, kPORT_MuxAlt2);

    /* PORTB16 (pin 62) is configured as SPI1_SOUT */
    PORT_SetPinMux(LCD_MOSI_PORT, LCD_MOSI_PIN, kPORT_MuxAlt2);

    /* PORTB17 (pin 63) is configured as SPI1_SIN */
    PORT_SetPinMux(LCD_MISO_PORT, LCD_MISO_PIN, kPORT_MuxAlt2);

    /* PORTB18 (pin 64) is configured as PTB18 */
    PORT_SetPinMux(LCD_RESET_PORT, LCD_RESET_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 65) is configured as PTB19 */
    PORT_SetPinMux(LCD_DCRS_PORT, LCD_DCRS_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 55) is configured as I2C0_SCL */
    PORT_SetPinMux(AUD_I2C_SCL_PORT, AUD_I2C_SCL_PIN, kPORT_MuxAlt2);

    /* PORTB20 (pin 66) is configured as PTB20 */
    PORT_SetPinMux(LCD_LED_PORT, LCD_LED_PIN, kPORT_MuxAsGpio);

    /* PORTB23 (pin 69) is configured as PTB23 */
    PORT_SetPinMux(BTN_MENU_PORT, BTN_MENU_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[23] = ((PORTB->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Passive Filter Enable: Passive input filter is disabled on the corresponding pin. */
                      | PORT_PCR_PFE(kPORT_PassiveFilterDisable));

    /* PORTB3 (pin 56) is configured as I2C0_SDA */
    PORT_SetPinMux(AUD_I2C_SDA_PORT, AUD_I2C_SDA_PIN, kPORT_MuxAlt2);

    /* PORTC0 (pin 70) is configured as PTC0 */
    PORT_SetPinMux(BTN_NEXT_PORT, BTN_NEXT_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[0] = ((PORTC->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Passive Filter Enable: Passive input filter is disabled on the corresponding pin. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterDisable));

    /* PORTC1 (pin 71) is configured as PTC1 */
    PORT_SetPinMux(BTN_SELECT_PORT, BTN_SELECT_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Passive Filter Enable: Passive input filter is disabled on the corresponding pin. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterDisable));

    /* PORTC10 (pin 82) is configured as I2C1_SCL */
    PORT_SetPinMux(BAT_I2C_SCL_PORT, BAT_I2C_SCL_PIN, kPORT_MuxAlt2);

    /* PORTC11 (pin 83) is configured as I2C1_SDA */
    PORT_SetPinMux(BAT_I2C_SDA_PORT, BAT_I2C_SDA_PIN, kPORT_MuxAlt2);

    /* PORTC13 (pin 85) is configured as PTC13 */
    PORT_SetPinMux(LOW_BATn_PORT, LOW_BATn_PIN, kPORT_MuxAsGpio);

    /* PORTC14 (pin 86) is configured as PTC14 */
    PORT_SetPinMux(PWR_EN_3V3_PORT, PWR_EN_3V3_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 90) is configured as PTC16 */
    PORT_SetPinMux(DONEn_PORT, DONEn_PIN, kPORT_MuxAsGpio);

    /* PORTC17 (pin 91) is configured as PTC17 */
    PORT_SetPinMux(DOK_PORT, DOK_PIN, kPORT_MuxAsGpio);

    /* PORTC18 (pin 92) is configured as PTC18 */
    PORT_SetPinMux(CHG_PORT, CHG_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 72) is configured as PTC2 */
    PORT_SetPinMux(BTN_PLAY_PORT, BTN_PLAY_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[2] = ((PORTC->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Passive Filter Enable: Passive input filter is disabled on the corresponding pin. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterDisable));

    /* PORTC3 (pin 73) is configured as PTC3 */
    PORT_SetPinMux(BTN_PREV_PORT, BTN_PREV_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[3] = ((PORTC->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Passive Filter Enable: Passive input filter is disabled on the corresponding pin. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterDisable));

    /* PORTC4 (pin 76) is configured as PTC4 */
    PORT_SetPinMux(PWR_EN_5Vn_PORT, PWR_EN_5Vn_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin 77) is configured as PTC5 */
    PORT_SetPinMux(LED_SENSE_3_3V_PORT, LED_SENSE_3_3V_PIN, kPORT_MuxAsGpio);
    /* Configure digital filter */
    PORT_EnablePinsDigitalFilter(
        /* Digital filter is configured on port D */
        PORTD,
        /* Digital filter is configured for PORTD0 */
        PORT_DFER_DFE_0_MASK,
        /* Disable digital filter */
        false);

    /* PORTD0 (pin 93) is configured as PTD0 */
    PORT_SetPinMux(DBG1_PORT, DBG1_PIN, kPORT_MuxAsGpio);

    /* PORTD1 (pin 94) is configured as PTD1 */
    PORT_SetPinMux(DBG2_PORT, DBG2_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin 95) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt2);

    /* PORTD3 (pin 96) is configured as PTD3 */
    PORT_SetPinMux(DBG4_PORT, DBG4_PIN, kPORT_MuxAsGpio);

    /* PORTD7 (pin 100) is configured as PTD7 */
    PORT_SetPinMux(SD_DETECT_PORT, SD_DETECT_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD7 (pin 100): Interrupt on either edge */
    PORT_SetPinInterruptConfig(SD_DETECT_PORT, SD_DETECT_PIN, kPORT_InterruptEitherEdge);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE0 (pin 1) is configured as SDHC0_D1 */
    PORT_SetPinMux(SD_DAT1_PORT, SD_DAT1_PIN, kPORT_MuxAlt4);

    PORTE->PCR[0] = ((PORTE->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE1 (pin 2) is configured as SDHC0_D0 */
    PORT_SetPinMux(SD_DAT0_PORT, SD_DAT0_PIN, kPORT_MuxAlt4);

    PORTE->PCR[1] = ((PORTE->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE2 (pin 3) is configured as SDHC0_DCLK */
    PORT_SetPinMux(SD_CLK_PORT, SD_CLK_PIN, kPORT_MuxAlt4);

    PORTE->PCR[2] = ((PORTE->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE3 (pin 4) is configured as SDHC0_CMD */
    PORT_SetPinMux(SD_CMD_PORT, SD_CMD_PIN, kPORT_MuxAlt4);

    PORTE->PCR[3] = ((PORTE->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE4 (pin 5) is configured as SDHC0_D3 */
    PORT_SetPinMux(SD_DAT3_PORT, SD_DAT3_PIN, kPORT_MuxAlt4);

    PORTE->PCR[4] = ((PORTE->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE5 (pin 6) is configured as SDHC0_D2 */
    PORT_SetPinMux(SD_DAT2_PORT, SD_DAT2_PIN, kPORT_MuxAlt4);

    PORTE->PCR[5] = ((PORTE->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_DeInitPins:
- options: {callFromInitBoot: 'false', prefix: '', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: I2S0, signal: TX_BCLK, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, identifier: ''}
  - {pin_num: '42', peripheral: I2S0, signal: TXD0, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA, identifier: ''}
  - {pin_num: '53', peripheral: FTM1, signal: 'QD_PH, A', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA, identifier: ''}
  - {pin_num: '54', peripheral: FTM1, signal: 'QD_PH, B', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB, identifier: ''}
  - {pin_num: '55', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, identifier: ''}
  - {pin_num: '56', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, identifier: ''}
  - {pin_num: '63', peripheral: SPI1, signal: SIN, pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, identifier: ''}
  - {pin_num: '62', peripheral: SPI1, signal: SOUT, pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, identifier: ''}
  - {pin_num: '68', peripheral: SPI2, signal: SOUT, pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, identifier: ''}
  - {pin_num: '82', peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, identifier: ''}
  - {pin_num: '83', peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, identifier: ''}
  - {pin_num: '3', peripheral: SDHC, signal: DCLK, pin_signal: ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2, identifier: '', pull_select: up,
    pull_enable: enable}
  - {pin_num: '5', peripheral: SDHC, signal: 'DATA, 3', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0, identifier: '', pull_select: up, pull_enable: enable}
  - {pin_num: '6', peripheral: SDHC, signal: 'DATA, 2', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0, identifier: '', pull_select: up, pull_enable: enable}
  - {pin_num: '2', peripheral: SDHC, signal: 'DATA, 0', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN, identifier: '',
    pull_select: up, pull_enable: enable}
  - {pin_num: '4', peripheral: SDHC, signal: CMD, pin_signal: ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT, identifier: '', pull_select: up,
    pull_enable: enable}
  - {pin_num: '1', peripheral: SDHC, signal: 'DATA, 1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, identifier: '', pull_select: up,
    pull_enable: enable}
  - {pin_num: '50', peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, identifier: ''}
  - {pin_num: '51', peripheral: OSC, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, identifier: ''}
  - {pin_num: '38', peripheral: SystemControl, signal: NMI, pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, identifier: ''}
  - {pin_num: '27', peripheral: DAC0, signal: OUT, pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, identifier: ''}
  - {pin_num: '11', peripheral: USB0, signal: DM, pin_signal: USB0_DM, identifier: ''}
  - {pin_num: '10', peripheral: USB0, signal: DP, pin_signal: USB0_DP, identifier: ''}
  - {pin_num: '12', peripheral: USB0, signal: VOUT33, pin_signal: VOUT33, identifier: ''}
  - {pin_num: '13', peripheral: USB0, signal: VREGIN, pin_signal: VREGIN, identifier: ''}
  - {pin_num: '96', peripheral: n/a, signal: disabled, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, identifier: ''}
  - {pin_num: '95', peripheral: n/a, signal: disabled, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL}
  - {pin_num: '94', peripheral: ADC0, signal: 'SE, 5b', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, identifier: ''}
  - {pin_num: '93', peripheral: n/a, signal: disabled, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, identifier: ''}
  - {pin_num: '92', peripheral: n/a, signal: disabled, pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, identifier: ''}
  - {pin_num: '91', peripheral: n/a, signal: disabled, pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, identifier: ''}
  - {pin_num: '90', peripheral: n/a, signal: disabled, pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, identifier: ''}
  - {pin_num: '85', peripheral: n/a, signal: disabled, pin_signal: PTC13/UART4_CTS_b/FB_AD26, identifier: ''}
  - {pin_num: '77', peripheral: n/a, signal: disabled, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, identifier: ''}
  - {pin_num: '76', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, identifier: '', direction: OUTPUT,
    gpio_init_state: 'true'}
  - {pin_num: '100', peripheral: n/a, signal: disabled, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, identifier: ''}
  - {pin_num: '73', peripheral: CMP1, signal: 'IN, 1', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, identifier: ''}
  - {pin_num: '72', peripheral: ADC0, signal: 'SE, 4b', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, identifier: ''}
  - {pin_num: '70', peripheral: ADC0, signal: 'SE, 14', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, identifier: ''}
  - {pin_num: '69', peripheral: n/a, signal: disabled, pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, identifier: ''}
  - {pin_num: '66', peripheral: n/a, signal: disabled, pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, identifier: ''}
  - {pin_num: '65', peripheral: n/a, signal: disabled, pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, identifier: ''}
  - {pin_num: '64', peripheral: n/a, signal: disabled, pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, identifier: ''}
  - {pin_num: '59', peripheral: ADC1, signal: 'SE, 15', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, identifier: ''}
  - {pin_num: '58', peripheral: ADC1, signal: 'SE, 14', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, identifier: ''}
  - {pin_num: '47', peripheral: ADC1, signal: 'SE, 17', pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK, identifier: ''}
  - {pin_num: '43', peripheral: CMP2, signal: 'IN, 1', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB, identifier: ''}
  - {pin_num: '44', peripheral: n/a, signal: disabled, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, identifier: ''}
  - {pin_num: '45', peripheral: n/a, signal: disabled, pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, identifier: ''}
  - {pin_num: '71', peripheral: LLWU, signal: 'P, 6', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, identifier: ''}
  - {pin_num: '86', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25, identifier: '', direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_DeInitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_DeInitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t gpioc_pin76_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 76)  */
    GPIO_PinInit(GPIOC, 4U, &gpioc_pin76_config);

    gpio_pin_config_t gpioc_pin86_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC14 (pin 86)  */
    GPIO_PinInit(GPIOC, 14U, &gpioc_pin86_config);

    /* PORTA12 (pin 42) is configured as I2S0_TXD0 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAlt6);

    /* PORTA13 (pin 43) is configured as CMP2_IN1 */
    PORT_SetPinMux(PORTA, 13U, kPORT_PinDisabledOrAnalog);

    /* PORTA14 (pin 44) is disabled */
    PORT_SetPinMux(PORTA, 14U, kPORT_PinDisabledOrAnalog);

    /* PORTA15 (pin 45) is disabled */
    PORT_SetPinMux(PORTA, 15U, kPORT_PinDisabledOrAnalog);

    /* PORTA17 (pin 47) is configured as ADC1_SE17 */
    PORT_SetPinMux(PORTA, 17U, kPORT_PinDisabledOrAnalog);

    /* PORTA18 (pin 50) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin 51) is configured as XTAL0 */
    PORT_SetPinMux(PORTA, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTA4 (pin 38) is configured as NMI_b */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTA5 (pin 39) is configured as I2S0_TX_BCLK */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt6);

    /* PORTB0 (pin 53) is configured as FTM1_QD_PHA */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt6);

    /* PORTB1 (pin 54) is configured as FTM1_QD_PHB */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt6);

    /* PORTB10 (pin 58) is configured as ADC1_SE14 */
    PORT_SetPinMux(PORTB, 10U, kPORT_PinDisabledOrAnalog);

    /* PORTB11 (pin 59) is configured as ADC1_SE15 */
    PORT_SetPinMux(PORTB, 11U, kPORT_PinDisabledOrAnalog);

    /* PORTB16 (pin 62) is configured as SPI1_SOUT */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt2);

    /* PORTB17 (pin 63) is configured as SPI1_SIN */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt2);

    /* PORTB18 (pin 64) is disabled */
    PORT_SetPinMux(PORTB, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTB19 (pin 65) is disabled */
    PORT_SetPinMux(PORTB, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTB2 (pin 55) is configured as I2C0_SCL */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt2);

    /* PORTB20 (pin 66) is disabled */
    PORT_SetPinMux(PORTB, 20U, kPORT_PinDisabledOrAnalog);

    /* PORTB22 (pin 68) is configured as SPI2_SOUT */
    PORT_SetPinMux(PORTB, 22U, kPORT_MuxAlt2);

    /* PORTB23 (pin 69) is disabled */
    PORT_SetPinMux(PORTB, 23U, kPORT_PinDisabledOrAnalog);

    /* PORTB3 (pin 56) is configured as I2C0_SDA */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt2);

    /* PORTC0 (pin 70) is configured as ADC0_SE14 */
    PORT_SetPinMux(PORTC, 0U, kPORT_PinDisabledOrAnalog);

    /* PORTC1 (pin 71) is configured as LLWU_P6 */
    PORT_SetPinMux(PORTC, 1U, kPORT_MuxAsGpio);

    /* PORTC10 (pin 82) is configured as I2C1_SCL */
    PORT_SetPinMux(PORTC, 10U, kPORT_MuxAlt2);

    /* PORTC11 (pin 83) is configured as I2C1_SDA */
    PORT_SetPinMux(PORTC, 11U, kPORT_MuxAlt2);

    /* PORTC13 (pin 85) is disabled */
    PORT_SetPinMux(PORTC, 13U, kPORT_PinDisabledOrAnalog);

    /* PORTC14 (pin 86) is configured as PTC14 */
    PORT_SetPinMux(PORTC, 14U, kPORT_MuxAsGpio);

    /* PORTC16 (pin 90) is disabled */
    PORT_SetPinMux(PORTC, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTC17 (pin 91) is disabled */
    PORT_SetPinMux(PORTC, 17U, kPORT_PinDisabledOrAnalog);

    /* PORTC18 (pin 92) is disabled */
    PORT_SetPinMux(PORTC, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTC2 (pin 72) is configured as ADC0_SE4b */
    PORT_SetPinMux(PORTC, 2U, kPORT_PinDisabledOrAnalog);

    /* PORTC3 (pin 73) is configured as CMP1_IN1 */
    PORT_SetPinMux(PORTC, 3U, kPORT_PinDisabledOrAnalog);

    /* PORTC4 (pin 76) is configured as PTC4 */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAsGpio);

    /* PORTC5 (pin 77) is disabled */
    PORT_SetPinMux(PORTC, 5U, kPORT_PinDisabledOrAnalog);

    /* PORTD0 (pin 93) is disabled */
    PORT_SetPinMux(PORTD, 0U, kPORT_PinDisabledOrAnalog);

    /* PORTD1 (pin 94) is configured as ADC0_SE5b */
    PORT_SetPinMux(PORTD, 1U, kPORT_PinDisabledOrAnalog);

    /* PORTD2 (pin 95) is disabled */
    PORT_SetPinMux(LED_DATA_PORT, LED_DATA_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTD3 (pin 96) is disabled */
    PORT_SetPinMux(PORTD, 3U, kPORT_PinDisabledOrAnalog);

    /* PORTD7 (pin 100) is disabled */
    PORT_SetPinMux(PORTD, 7U, kPORT_PinDisabledOrAnalog);

    /* PORTE0 (pin 1) is configured as SDHC0_D1 */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt4);

    PORTE->PCR[0] = ((PORTE->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE1 (pin 2) is configured as SDHC0_D0 */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt4);

    PORTE->PCR[1] = ((PORTE->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE2 (pin 3) is configured as SDHC0_DCLK */
    PORT_SetPinMux(PORTE, 2U, kPORT_MuxAlt4);

    PORTE->PCR[2] = ((PORTE->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE3 (pin 4) is configured as SDHC0_CMD */
    PORT_SetPinMux(PORTE, 3U, kPORT_MuxAlt4);

    PORTE->PCR[3] = ((PORTE->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE4 (pin 5) is configured as SDHC0_D3 */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAlt4);

    PORTE->PCR[4] = ((PORTE->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE5 (pin 6) is configured as SDHC0_D2 */
    PORT_SetPinMux(PORTE, 5U, kPORT_MuxAlt4);

    PORTE->PCR[5] = ((PORTE->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
